### ISSUE TITLE
Dependency failed on starting

### ISSUE THREAD

**Issue by Gywem** [philcockfield/ui-harness#62]
Hi!

I congrats you for this amazing library for testing manually our components.

I am trying to set it up in my project but I am getting a dependency failing when starting.

````
module.js:341
    throw err;
    ^

Error: Cannot find module 'memory-fs'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/XXX/node_modules/ui-harness/lib/server/webpack-builder.js:23:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/XXX/node_modules/ui-harness/lib/server/build.js:27:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
````

Is not supposed that ui-harness is including such depencency/es?

Thanks

**Comment by Gywem** [comment]
It is the node version v5.9.1.

**Comment by philcockfield** [comment]
Hmm - weird.  Lemme try it out on `5.9.1`.

**Comment by philcockfield** [comment]
Hey, sorry about this @Gywem.  Not sure why that was working here and on the build-server, the reference should have come in via WebPack.  None-the-less, I've added it as an explicit reference in the `package.json`.

Does that work for you now.
